name: Auto Update MOEX Datasets

on:
  schedule:
    - cron: "0 3 * * *"  # каждый день в 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # ✅ ВАЖНО: даём права на push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run update script
        run: python fetch_and_update.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*.csv
          git commit -m "Auto update MOEX fund datasets" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

