name: Run Dual Momentum Strategy

on:
  schedule:
    # Каждое воскресенье в 10:00 UTC
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  run_strategy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn

    - name: Run strategy
      id: run_strategy
      run: |
        python strategy_dual_momentum.py > result.txt
        tail -n 10 result.txt

    - name: Send result to Telegram
      uses: appleboy/telegram-action@v0.2.0
      with:
        to: ${{ secrets.TG_CHAT_ID }}
        token: ${{ secrets.TG_BOT_TOKEN }}
        message: |
          $(tail -n 10 result.txt)
          📊 Файл с результатами: dual_momentum_portfolio.csv
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
