name: Dual Momentum Signal

on:
  schedule:
    # Ежедневно в 10:00 по UTC (13:00 МСК)
    - cron: "10 07 * * *"
  workflow_dispatch:  # позволяет запустить вручную из GitHub UI

jobs:
  run_strategy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas numpy requests

      - name: Run Dual Momentum Strategy
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python strategy_dual_momentum.py
